"""add email_notifications

Revision ID: 23c523f8b7c2
Revises: 20250130_user_initial
Create Date: 2025-07-04 02:17:58.517071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c523f8b7c2'
down_revision: Union[str, None] = '20250130_user_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('email_notifications', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'email_notifications')
    # ### end Alembic commands ###
