"""add draws to player_ratings

Revision ID: 516dd34e4570
Revises: 001_initial_duels
Create Date: 2025-07-10 12:37:30.207938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516dd34e4570'
down_revision: Union[str, None] = '001_initial_duels'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_ratings', sa.Column('draws', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_ratings', 'draws')
    # ### end Alembic commands ###
