"""romm

Revision ID: f19950d17caf
Revises: 516dd34e4570
Create Date: 2025-07-16 14:06:30.127139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19950d17caf'
down_revision: Union[str, None] = '516dd34e4570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duels', sa.Column('room_code', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_duels_room_code'), 'duels', ['room_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_duels_room_code'), table_name='duels')
    op.drop_column('duels', 'room_code')
    # ### end Alembic commands ###
