"""ready

Revision ID: 3f98ce96083c
Revises: f19950d17caf
Create Date: 2025-07-16 15:31:38.180942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f98ce96083c'
down_revision: Union[str, None] = 'f19950d17caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duels', sa.Column('player_one_ready', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('duels', sa.Column('player_two_ready', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duels', 'player_two_ready')
    op.drop_column('duels', 'player_one_ready')
    # ### end Alembic commands ###
