"""initial_duels_tables

Revision ID: 001_initial_duels
Revises: 
Create Date: 2025-01-30 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001_initial_duels'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duels',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('problem_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'generating_problem', 'in_progress', 'completed', 'timed_out', 'cancelled', 'error', 'failed_generation', name='duelstatus', native_enum=False), nullable=False),
    sa.Column('player_one_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('player_two_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('player_one_code', sa.String(), nullable=True),
    sa.Column('player_two_code', sa.String(), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_ratings',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('elo_rating', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('total_matches', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_ratings')
    op.drop_table('duels')
    op.execute('DROP TYPE duelstatus')
    # ### end Alembic commands ### 